import pino from "pino";
import { config } from "../../config/config.js";

export const logger = pino({
  level: config.get("app.logLevel"),
  redact: {
    paths: [
      "req.headers.authorization",
      "req.headers.cookie",
      "req.headers['x-csrf-token']",
      "req.body.password",
      "req.body.token",
      "req.body.credential",
      "password",
      "token",
      "credential",
      "authorization",
      "cookie",
      "rawToken",
      "csrfToken",
      "signedUrl",
      "objectKey",
      "email",
      "invitedEmail",
      "normalizedEmail",
      "recipientEmail",
      "*.password",
      "*.token",
      "*.credential",
      "*.authorization",
      "*.cookie",
      "*.rawToken",
      "*.csrfToken",
      "*.url",
      "*.signedUrl",
      "*.objectKey",
      "*.email",
      "*.invitedEmail",
      "*.normalizedEmail",
      "*.recipientEmail",
      "err.sql",
      "err.parameters",
      "err.fields",
    ],
    censor: "[REDACTED]",
  },
});
